### ISSUE TITLE
Problems with the packages versions

### ISSUE THREAD

**Issue by miguel-angel-monjas** [sergiocalde94/Data-And-Model-Drift-Checker#8]
Hi, I'm trying to run the notebooks provided in the repo and I'm not being able to. I've created a new conda virtual environment with Python 3.7
```
conda create -n pydrift python=3.7
conda activate pydrift
conda install -c conda-forge pydrift
```
When I try to run a simple import, I get an error:
```
>>> import pandas as pd
>>> from sklearn.model_selection import train_test_split
>>> from pydrift import DataDriftChecker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pydrift/lib/python3.7/site-packages/pydrift/__init__.py", line 1, in <module>
    from .core.drift_checker import (DriftChecker,
  File "/home/ubuntu/anaconda3/envs/pydrift/lib/python3.7/site-packages/pydrift/core/drift_checker.py", line 16, in <module>
    from .interpretable_drift import InterpretableDrift
  File "/home/ubuntu/anaconda3/envs/pydrift/lib/python3.7/site-packages/pydrift/core/interpretable_drift.py", line 19, in <module>
    from shap.common import SHAPError
ModuleNotFoundError: No module named 'shap.common'
```
What am I doing wrong?

Thanks

  // M.A. Monjas

**Comment by sergiocalde94** [comment]
Hi @miguel-angel-monjas, sorry for the very late response, I lost the notification 🥺

Shap removed the SHAPError for newer versions and I updated pydrift in order to works fine in this commit: https://github.com/sergiocalde94/pydrift/commit/da62fbc055093605442f48accfa7a1f752aa3f3a

The problem was with conda-forge (with pip install there wasn't this problem), it supposes to automatically updates the packages when I add some git tags but this time wasn't the case...

I've already updated it and you can reinstall pydrift and run the examples.

Sorry for the inconvenience and thanks for using pydrift! 🙏.
